binovo_elkar_backups:
    resource: "@BinovoElkarBackupBundle/Controller"
    type:     annotation
    prefix:   /
login_check:
    path:   /login_check
logout:
    path: /logout
binovo_elkar_tahoe:
    resource: "@BinovoElkarTahoeBundle/Controller/"
    type:     annotation

api_get_users:
    pattern:  /api/users
    defaults: { _controller: BinovoElkarBackupBundle:Api:getUsers, _format: json }
    requirements:
        _method: GET
api_get_user:
    pattern:  /api/users/{id}
    defaults: { _controller: BinovoElkarBackupBundle:Api:getUser, _format: json }
    requirements:
        _method: GET
        id: "\d+"