binovo_elkar_backups:
    resource: "@BinovoElkarBackupBundle/Controller"
    type:     annotation
    prefix:   /
login_check:
    path:   /login_check
logout:
    path: /logout
binovo_elkar_tahoe:
    resource: "@BinovoElkarTahoeBundle/Controller/"
    type:     annotation
binovo_elkar_api:
    resource: "@BinovoElkarBackupBundle/Api"
    type:     rest
    prefix:   /api
